# Path settings
root: .
destination: ./site
plugins: ./plugins
templates: ./templates
path_template: "{year}/{month}/{day}"

#site settings
title: 标题
author: Eric 杨
email: your-email@domain.com
url: http://yourdomain.com
paginate: 5
time_zone: Asia/Shanghai

# Serving
host: 127.0.0.1
port: 5000
